all: programs/zad1_fifo programs/zad1_lifo programs/zad2_linked_list programs/zad3_circular_linked_list

programs/zad1_fifo: src/zad1_fifo.cpp
	g++ -o programs/zad1_fifo src/zad1_fifo.cpp

programs/zad1_lifo: src/zad1_lifo.cpp
	g++ -o programs/zad1_lifo src/zad1_lifo.cpp

programs/zad2_linked_list: src/zad2_linked_list.cpp
	g++ -o programs/zad2_linked_list src/zad2_linked_list.cpp

programs/zad3_circular_linked_list: src/zad3_circular_linked_list.cpp
	g++ -o programs/zad3_circular_linked_list src/zad3_circular_linked_list.cpp
